version: '2'
services:
  db:
    image: mysql
    environment:
                - MYSQL_ALLOW_EMPTY_PASSWORD=yes
                - MYSQL_USER=root
                - MYSQL_DATABASE=loja
  web:
    image: rafanercessian/aplicacao:final2-roteiro 
    ports:
      - "80:80"
    depends_on:
      - db
